spring:
  datasource:
    #MySQL连接信息
    url: jdbc:mysql://localhost:3306/shirotest?serverTimezone=GMT%2B8
    # 账号
    username: root
    # 密码
    password: root
    # 驱动
    driver-class-name: com.mysql.jdbc.Driver
