spring:
  datasource:
    test:               # master 数据源配置(test库)
      url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=GMT%2B8
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver
    testB:              # second 数据源配置(testb库)
      url: jdbc:mysql://127.0.0.1:3306/testb?serverTimezone=GMT%2B8
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver

#mybatis:
#  mapper-locations: classpath:mapper/master/*.xml
#  type-aliases-package: web.entity    #对应实体类路径
logging:
  level:
    web.dao.test.StudentDao.**: debug