eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #单机版
      defaultZone: http://localhost:7001/eureka
      # 集群版
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    hostname: cloud-gateway-test9526
server:
  port: 9526
spring:
  application:
    name: gateway-consumer9526
  cloud:
    gateway:
      routes:
        - id: test_routh1 #payment_routh    #路由的ID，没有固定规则但要求唯一，简易配合服务名
          uri: lb://CLOUD-PROVIDE8888-SERVICE         #匹配后提供服务的路由地址
          predicates:
            - Path=/test/getInfo/**          #断言，路径相匹配的进行路由

        - id: test_routh2
          uri: lb://CLOUD-PROVIDE8888-SERVICE
          predicates:
            - Path=/test/getMessage/**